cc_binary(
  name = "kfs",
  deps = ["@com_google_absl//absl/container:flat_hash_map"],
  srcs = ["kfs.cpp", "kfs.hpp"]
)

cc_binary(
  name = "msl",
  srcs = ["make_struct_lookup.cpp"]
)

cc_binary(
  name = "generate_fasta",
  srcs = ["generate_fasta.cpp"]
)